export const dummySponsors = [
  {
    name: "Impi Brewing",
    image: "/img/impi.jpg",
    website: "google.com",
    facebook: "google.com",
    instagram: "google.com",
    email: "google.com",
    address: "google.com",
    phone: "93075875",
    description:
      "Opened in 2017, Impi brings South African flair to the Western Australian Beer scene. Our family owned brewery is about creating beer with scientific … See more",
  },
  {
    name: "Impi Brewing",
    image: "/img/impi.jpg",
    website: "google.com",
    facebook: "google.com",
    instagram: "google.com",
    email: "google.com",
    address: "google.com",
    phone: "93075875",
    description:
      "Opened in 2017, Impi brings South African flair to the Western Australian Beer scene. Our family owned brewery is about creating beer with scientific … See more",
  },
  {
    name: "Impi Brewing",
    image: "/img/impi.jpg",
    website: "google.com",
    facebook: "google.com",
    instagram: "google.com",
    email: "google.com",
    address: "google.com",
    phone: "93075875",
    description:
      "Opened in 2017, Impi brings South African flair to the Western Australian Beer scene. Our family owned brewery is about creating beer with scientific … See more",
  },
  {
    name: "Impi Brewing",
    image: "/img/impi.jpg",
    website: "google.com",
    facebook: "google.com",
    instagram: "google.com",
    email: "google.com",
    address: "google.com",
    phone: "93075875",
    description:
      "Opened in 2017, Impi brings South African flair to the Western Australian Beer scene. Our family owned brewery is about creating beer with scientific … See more",
  },
  {
    name: "Impi Brewing",
    image: "/img/impi.jpg",
    website: "google.com",
    facebook: "google.com",
    instagram: "google.com",
    email: "google.com",
    address: "google.com",
    phone: "93075875",
    description:
      "Opened in 2017, Impi brings South African flair to the Western Australian Beer scene. Our family owned brewery is about creating beer with scientific … See more",
  },
  {
    name: "Impi Brewing",
    image: "/img/impi.jpg",
    website: "google.com",
    facebook: "google.com",
    instagram: "google.com",
    email: "google.com",
    address: "google.com",
    phone: "93075875",
    description:
      "Opened in 2017, Impi brings South African flair to the Western Australian Beer scene. Our family owned brewery is about creating beer with scientific … See more",
  },
  {
    name: "Impi Brewing",
    image: "/img/impi.jpg",
    website: "google.com",
    facebook: "google.com",
    instagram: "google.com",
    email: "google.com",
    address: "google.com",
    phone: "93075875",
    description:
      "Opened in 2017, Impi brings South African flair to the Western Australian Beer scene. Our family owned brewery is about creating beer with scientific … See more",
  },
  {
    name: "Impi Brewing",
    image: "/img/impi.jpg",
    website: "google.com",
    facebook: "google.com",
    instagram: "google.com",
    email: "google.com",
    address: "google.com",
    phone: "93075875",
    description:
      "Opened in 2017, Impi brings South African flair to the Western Australian Beer scene. Our family owned brewery is about creating beer with scientific … See more",
  },
  {
    name: "Impi Brewing",
    image: "/img/impi.jpg",
    website: "google.com",
    facebook: "google.com",
    instagram: "google.com",
    email: "google.com",
    address: "google.com",
    phone: "93075875",
    description:
      "Opened in 2017, Impi brings South African flair to the Western Australian Beer scene. Our family owned brewery is about creating beer with scientific … See more",
  },
  {
    name: "Impi Brewing",
    image: "/img/impi.jpg",
    website: "google.com",
    facebook: "google.com",
    instagram: "google.com",
    email: "google.com",
    address: "google.com",
    phone: "93075875",
    description:
      "Opened in 2017, Impi brings South African flair to the Western Australian Beer scene. Our family owned brewery is about creating beer with scientific … See more",
  },
  {
    name: "Impi Brewing",
    image: "/img/impi.jpg",
    website: "google.com",
    facebook: "google.com",
    instagram: "google.com",
    email: "google.com",
    address: "google.com",
    phone: "93075875",
    description:
      "Opened in 2017, Impi brings South African flair to the Western Australian Beer scene. Our family owned brewery is about creating beer with scientific … See more",
  },
  {
    name: "Impi Brewing",
    image: "/img/impi.jpg",
    website: "google.com",
    facebook: "google.com",
    instagram: "google.com",
    email: "google.com",
    address: "google.com",
    phone: "93075875",
    description:
      "Opened in 2017, Impi brings South African flair to the Western Australian Beer scene. Our family owned brewery is about creating beer with scientific … See more",
  },
];
