export const dummySponsors = [
  {
    name: "Impi Brewing",
    image: "/img/impi.jpg",
    facebook: "https://www.google.com",
    instagram: "https://www.google.com",
    email: "test@test.com",
    address: "https://www.google.com",
    phone: "0435555555",
    description:
      "Opened in 2017, Impi brings South African flair to the Western Australian Beer scene. Our family owned brewery is about creating beer with scientific ",
  },
  {
    name: "Impi Brewing",
    image: "/img/impi.jpg",
    website: "https://www.google.com",
    facebook: "https://www.google.com",
    instagram: "https://www.google.com",
    email: "test@test.com",
    address: "https://www.google.com",
    phone: "0435555555",
    description:
      "Opened in 2017, Impi brings South African flair to the Western Australian Beer scene. Our family owned brewery is about creating beer with scientific ",
  },
  {
    name: "Impi Brewing",
    image: "/img/impi.jpg",
    website: "https://www.google.com",
    facebook: "https://www.google.com",
    instagram: "https://www.google.com",
    email: "test@test.com",
    address: "https://www.google.com",
    phone: "0435555555",
    description:
      "Opened in 2017, Impi brings South African flair to the Western Australian Beer scene. Our family owned brewery is about creating beer with scientific ",
  },
  {
    name: "Impi Brewing",
    image: "/img/impi.jpg",
    website: "https://www.google.com",
    facebook: "https://www.google.com",
    instagram: "https://www.google.com",
    email: "test@test.com",
    address: "https://www.google.com",
    phone: "0435555555",
    description:
      "Opened in 2017, Impi brings South African flair to the Western Australian Beer scene. Our family owned brewery is about creating beer with scientific ",
  },
  {
    name: "Impi Brewing",
    image: "/img/impi.jpg",
    website: "https://www.google.com",
    facebook: "https://www.google.com",
    instagram: "https://www.google.com",
    email: "test@test.com",
    address: "https://www.google.com",
    phone: "0435555555",
    description:
      "Opened in 2017, Impi brings South African flair to the Western Australian Beer scene. Our family owned brewery is about creating beer with scientific ",
  },
  {
    name: "Impi Brewing",
    image: "/img/impi.jpg",
    website: "https://www.google.com",
    facebook: "https://www.google.com",
    instagram: "https://www.google.com",
    email: "test@test.com",
    address: "https://www.google.com",
    phone: "0435555555",
    description:
      "Opened in 2017, Impi brings South African flair to the Western Australian Beer scene. Our family owned brewery is about creating beer with scientific ",
  },
  {
    name: "Impi Brewing",
    image: "/img/impi.jpg",
    website: "https://www.google.com",
    facebook: "https://www.google.com",
    instagram: "https://www.google.com",
    email: "test@test.com",
    address: "https://www.google.com",
    phone: "0435555555",
    description:
      "Opened in 2017, Impi brings South African flair to the Western Australian Beer scene. Our family owned brewery is about creating beer with scientific ",
  },
  {
    name: "Impi Brewing",
    image: "/img/impi.jpg",
    website: "https://www.google.com",
    facebook: "https://www.google.com",
    instagram: "https://www.google.com",
    email: "test@test.com",
    address: "https://www.google.com",
    phone: "0435555555",
    description:
      "Opened in 2017, Impi brings South African flair to the Western Australian Beer scene. Our family owned brewery is about creating beer with scientific ",
  },
  {
    name: "Impi Brewing",
    image: "/img/impi.jpg",
    website: "https://www.google.com",
    facebook: "https://www.google.com",
    instagram: "https://www.google.com",
    email: "test@test.com",
    address: "https://www.google.com",
    phone: "0435555555",
    twitter: "https://www.google.com",
    description:
      "Opened in 2017, Impi brings South African flair to the Western Australian Beer scene. Our family owned brewery is about creating beer with scientific ",
  },
  {
    name: "Impi Brewing",
    image: "/img/impi.jpg",
    website: "https://www.google.com",
    facebook: "https://www.google.com",
    instagram: "https://www.google.com",
    email: "test@test.com",
    address: "https://www.google.com",
    phone: "0435555555",
    twitter: "https://www.google.com",
    description:
      "Opened in 2017, Impi brings South African flair to the Western Australian Beer scene. Our family owned brewery is about creating beer with scientific ",
  },
  {
    name: "Impi Brewing",
    image: "/img/impi.jpg",
    website: "https://www.google.com",
    facebook: "https://www.google.com",
    instagram: "https://www.google.com",
    email: "test@test.com",
    address: "https://www.google.com",
    phone: "0435555555",
    description:
      "Opened in 2017, Impi brings South African flair to the Western Australian Beer scene. Our family owned brewery is about creating beer with scientific ",
  },
  {
    name: "Impi Brewing",
    image: "/img/impi.jpg",
    website: "https://www.google.com",
    facebook: "https://www.google.com",
    instagram: "https://www.google.com",
    twitter: "https://www.google.com",
    email: "test@test.com",
    address: "https://www.google.com",
    phone: "0435555555",
    description:
      "Opened in 2017, Impi brings South African flair to the Western Australian Beer scene. Our family owned brewery is about creating beer with scientific ",
  },
];
