import Head from "next/head";
import Footer from "../components/Footer";
import Hero from "../components/Hero";
import ThreeColumnContent from "../components/ThreeColumnContent";
import SideContent from "../components/SideContent";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <ThreeColumnContent />
      <SideContent />
      <Footer />
    </div>
  );
}
